---
title: "CCBR1109_secondary_analysis.RMD"
author: "Samantha Sevilla"
date: "9/21/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(ggplot2)
library("org.Mm.eg.db")
library(ggpubr)
```

Set directories
```{r setup, include=FALSE}
analysis_dir ="~/../../Volumes/ccbr1109/analysis/"
deg_dir="~/../../Volumes/ccbr1109/rnaseq/"
resource_dir ="~/../../Volumes/ccbr1109/resources/"
de_gene_dir=paste0(analysis_dir,"venn/")
deg_merged_input=paste0(analysis_dir,"deg_data/merged_deg_fc_DESeq2_20210811.txt")

```

Set global variables
```{r}
p_val = 0.05
species = "mouse" #Homo sapiens
fc = 1.5

compare_list = c("GCN1_SH2.SCR","HNPK_SH1.SCR","HNPK_SH2.SCR")
cat_list = c("GCN1_SH2","HNPK_SH1","HNPK_SH2")

```

#prep gene lists
```{r}
#read in upreg ensemblids, create df
gene_sig=data.frame()
gene_nonsig=data.frame()

for (c_id in compare_list){
    #process sig gene list
    tmp_df = as.data.frame(read.csv(paste0(de_gene_dir,"genes_up_",c_id,".csv")))
    
    #annotate ensemble ids with gene name
    symbols <- mapIds(org.Mm.eg.db, keys = sapply(strsplit(tmp_df$gene,".", fixed=TRUE), `[`, 1),
                      keytype = "ENSEMBL", column="SYMBOL", multiVals = "first")
    
    for (rowid in rownames(tmp_df)){
      gene_sig[tmp_df[rowid,"gene"],paste0(c_id,".fc")] = tmp_df[rowid,paste0(c_id,".fc")] 
      gene_sig[tmp_df[rowid,"gene"],paste0(c_id,".fdr")] = tmp_df[rowid,paste0(c_id,".fdr")]
      gene_sig[tmp_df[rowid,"gene"],"eid"]=strsplit(tmp_df[rowid,"gene"],".",fixed=TRUE)[[1]][1]
      gene_sig[tmp_df[rowid,"gene"],"symbol"]=symbols[gene_sig[tmp_df[rowid,"gene"],"eid"]][[1]]
    }
    
    #process non-sig ist
    tmp_df = as.data.frame(read.csv(paste0(de_gene_dir,"genes_nonde_",c_id,".csv")))
    
    #annotate ensemble ids with gene name
    symbols <- mapIds(org.Mm.eg.db, keys = sapply(strsplit(tmp_df$gene,".", fixed=TRUE), `[`, 1),
                      keytype = "ENSEMBL", column="SYMBOL", multiVals = "first")
    
    for (rowid in rownames(tmp_df)){
      gene_nonsig[tmp_df[rowid,"gene"],paste0(c_id,".fc")] = tmp_df[rowid,paste0(c_id,".fc")] 
      gene_nonsig[tmp_df[rowid,"gene"],paste0(c_id,".fdr")] = tmp_df[rowid,paste0(c_id,".fdr")]
      gene_nonsig[tmp_df[rowid,"gene"],"eid"]=strsplit(tmp_df[rowid,"gene"],".",fixed=TRUE)[[1]][1]
      gene_nonsig[tmp_df[rowid,"gene"],"symbol"]=symbols[gene_nonsig[tmp_df[rowid,"gene"],"eid"]][[1]]
    }
}

#read in gene %c reference
ref_df = read.csv(paste0(resource_dir,"mm10.3prime_UTR.ACGT.tsv"),sep="\t")
```

#plot histograms
```{r}
determine_plot_c<-function(list.in,c_id){
  sig_gene = subset(ref_df, gene_name %in% list.in[!is.na(list.in)])
  # Histogram with density plot
  p = ggplot(sig_gene, aes(x=perc_C)) + 
    geom_histogram(aes(y=..density..), colour="black", fill="white")+
    geom_density(alpha=.2, fill="#FF6666") +
    geom_vline(aes(xintercept=mean(perc_C)),
            color="blue", linetype="dashed", size=1) + 
    labs(title=paste(c_id),
        x =paste0("Percent C: Mean (",round(mean(sig_gene$perc_C),2),"%)")) + 
    ylim(0, 0.1)
  return(p)
}

#create lists
l_up =(gene_sig %>% filter(if_all(paste0(compare_list[2],".fc"), ~ !is.na(.x))))
l_nonde = (gene_nonsig %>% filter(if_all(paste0(compare_list[2],".fc"), ~ !is.na(.x))))

#scale nonde to number in upreg
l_nonde_sub = sample (subset(l_nonde,!is.na(symbol) & 
                               symbol %in% ref_df$gene_name)$symbol, #symbols is not NA and symbol is found in refdf
                      size=length(subset(l_up,!is.na(symbol) & symbol %in% ref_df$gene_name)$symbol), replace =F)

#plot HNPK upreg to nonde
p1 = determine_plot_c(l_up$symbol,
                      paste0("Significantly Upregulated"))
p2 = determine_plot_c(l_nonde$symbol,
                     paste0(" Non-significantly differentially regulated"))
pf = ggarrange(p1,p2,
               labels = c("A", "B"),
               ncol = 2, nrow = 1)
pf = annotate_figure(pf, top = text_grob("Histograms of HNPK_SH1 to SCR", 
                face = "bold", size = 14))
print(pf)
file.in = paste0(analysis_dir,"c_content/","hnpksh1_up_to_nonde.png")
ggsave(filename = file.in, 
           height = 8.90, width = 12.80, device = "png", plot = pf)

#plot HNPK upreg to scaled nonde
p1 = determine_plot_c(l_up$symbol,
                      paste0("Significantly Upregulated"))
p2 = determine_plot_c(l_nonde_sub,
                     paste0(" Non-significantly differentially regulated (scaled)"))
pf = ggarrange(p1,p2,
               labels = c("A", "B"),
               ncol = 2, nrow = 1)
pf = annotate_figure(pf, top = text_grob("Histograms of HNPK_SH1 to SCR", 
                face = "bold", size = 14))
print(pf)
file.in = paste0(analysis_dir,"c_content/","hnpksh1_up_to_nonde_sub.png")
ggsave(filename = file.in, 
           height = 8.90, width = 12.80, device = "png", plot = pf)
```

#run statistics
```{r}
determine_stats_c<-function(list1.in,list2.in){
  c1 = subset(ref_df, gene_name %in% list1.in[!is.na(list1.in)])$perc_C
  c2 = subset(ref_df, gene_name %in% list2.in[!is.na(list2.in)])$perc_C

  #print general stats
  list_stats<-function(list.name,l1){
    print(paste0("***", list.name, " Stats ***"))
    print(paste0("Min:", round(min(l1),2)))
    print(paste0("Max:", round(max(l1),2)))
    print(paste0("Mean:", round(mean(l1),2)))
    print(paste0("Median:", round(median(l1),2)))
    print(paste0("Number of genes:",length(l1)))
  }
  
  list_stats("Upregulated", c1)
  list_stats("Non-regulated",c2)
  
  #determine sig with Kolmogorov-Smirnov test
  ks.test(c1, c2)
}

determine_stats_c(l_up,l_nonde)
determine_stats_c(l_up,l_nonde_sub)
```

#determine overlap between . HNRNPK_SH1 and GCN1_SH2 using FC as 1.5
```{r}
overlap_lists<-function(sample1,sample2,fc_in,fdr_in=""){
  merged_df = read.csv(deg_merged_input,sep="\t")

  if(fdr_in==""){
    #subset for fc, fdr
    de_down = subset(merged_df, get(paste0(sample1,".fc"))<=-fc_in) %>%
            subset(get(paste0(sample2,".fc"))<=-fc_in )
    de_up = subset(merged_df, get(paste0(sample1,".fc"))>=fc_in) %>%
            subset(get(paste0(sample2,".fc"))>=fc_in )
  } else{
     #subset for fc, fdr
    de_down = subset(merged_df, get(paste0(sample1,".fc"))<=-fc_in) %>%
            subset(get(paste0(sample1,".fdr"))<=fdr_in) %>%
            subset(get(paste0(sample2,".fc"))<=-fc_in ) %>%
            subset(get(paste0(sample2,".fdr"))<=fdr_in)
    de_up = subset(merged_df, get(paste0(sample1,".fc"))>=fc_in) %>%
            subset(get(paste0(sample1,".fdr"))<=fdr_in) %>%
            subset(get(paste0(sample2,".fc"))>=fc_in ) %>%
            subset(get(paste0(sample2,".fdr"))<=fdr_in)
  }
  
  de_final = rbind(de_down,de_up)
  print(paste0("N genes: ", nrow(de_final)))
  return(de_final)
}

final_df=overlap_lists("GCN1_SH2.SCR","HNPK_SH1.SCR", 1.5)
write.csv(final_df,paste0(analysis_dir,"venn/de_fc1.5_overlap_GNC1andHNPK_SH1.csv"))

final_df=overlap_lists("GCN1_SH2.SCR","HNPK_SH1.SCR",1.5, 0.05)
write.csv(final_df,paste0(analysis_dir,"venn/de_fc1.5andfdr0.05_overlap_GNC1andHNPK_SH1.csv"))
```

